/* 神奇八號球 —— 模式與清單資料。
 *
 * 要新增模式，往 MODES 推一筆就好，選單、標題、字級、配色都會自動跟上：
 *
 *   { id, icon, label, size?, hint, initial, noRepeat?, items | roll }
 *
 *   size     "md" 詞彙 / "lg" YES-NO / "xl" 單一符號或數字；省略為預設字級
 *   noRepeat 避開連續抽到同一項（清單長度 <= 2 時自動忽略）
 *   items    { primary, secondary, tone }，tone 對應下面的 TONES
 *   roll     選項太多不適合列清單時，改用它直接算（有 roll 就不需要 items）
 */

const TONES = {
  yes:     "#4ade80",
  no:      "#f87171",
  maybe:   "#fbbf24",
  snack:   "#fbbf24",
  noodle:  "#fb923c",
  rice:    "#a3e635",
  intl:    "#f472b6",
  light:   "#5eead4",
  tea:     "#86efac",
  coffee:  "#c8a165",
  fizz:    "#7dd3fc",
  sweet:   "#fda4af",
  asia:    "#fca5a5",
  europe:  "#93c5fd",
  america: "#fcd34d",
  africa:  "#fdba74",
  mideast: "#a7f3d0",
  perform: "#c4b5fd",
  action:  "#fca5a5",
  talk:    "#7dd3fc",
  task:    "#fcd34d",
  silly:   "#f0abfc"
};

const MODES = [
  {
    id: "oracle", icon: "🎱", label: "神奇八號球",
    hint: "心中默想問題，然後點一下球",
    initial: { primary: "Ask a question", secondary: "問個問題吧" },
    items: [
      { primary: "It is certain",             secondary: "這是必然", tone: "yes" },
      { primary: "It is decidedly so",        secondary: "肯定是的", tone: "yes" },
      { primary: "Without a doubt",           secondary: "不用懷疑", tone: "yes" },
      { primary: "Yes, definitely",           secondary: "毫無疑問", tone: "yes" },
      { primary: "You may rely on it",        secondary: "你能依靠它", tone: "yes" },
      { primary: "As I see it, yes",          secondary: "如我所見，是的", tone: "yes" },
      { primary: "Most likely",               secondary: "很有可能", tone: "yes" },
      { primary: "Outlook good",              secondary: "外表很好", tone: "yes" },
      { primary: "Yes",                       secondary: "是的", tone: "yes" },
      { primary: "Signs point to yes",        secondary: "種種跡象指出「是的」", tone: "yes" },
      { primary: "Reply hazy, try again",     secondary: "回覆籠統，再試試", tone: "maybe" },
      { primary: "Ask again later",           secondary: "待會再問", tone: "maybe" },
      { primary: "Better not tell you now",   secondary: "最好現在不告訴你", tone: "maybe" },
      { primary: "Cannot predict now",        secondary: "現在無法預測", tone: "maybe" },
      { primary: "Concentrate and ask again", secondary: "專心再問一遍", tone: "maybe" },
      { primary: "Don't count on it",         secondary: "想的美", tone: "no" },
      { primary: "My reply is no",            secondary: "我的回覆是「不」", tone: "no" },
      { primary: "My sources say no",         secondary: "我的來源說「不」", tone: "no" },
      { primary: "Outlook not so good",       secondary: "前景不太好", tone: "no" },
      { primary: "Very doubtful",             secondary: "很可疑", tone: "no" }
    ]
  },
  {
    id: "food", icon: "🍽️", label: "今天吃什麼", size: "md",
    hint: "肚子餓了？點一下球",
    initial: { primary: "吃什麼？", secondary: "點一下球" },
    noRepeat: true,
    items: [
      { primary: "滷肉飯",    secondary: "小吃", tone: "snack" },
      { primary: "鹹酥雞",    secondary: "小吃", tone: "snack" },
      { primary: "蚵仔煎",    secondary: "小吃", tone: "snack" },
      { primary: "肉圓",     secondary: "小吃", tone: "snack" },
      { primary: "臭豆腐",    secondary: "小吃", tone: "snack" },
      { primary: "大腸包小腸",  secondary: "小吃", tone: "snack" },
      { primary: "胡椒餅",    secondary: "小吃", tone: "snack" },
      { primary: "蔥抓餅",    secondary: "小吃", tone: "snack" },
      { primary: "車輪餅",    secondary: "小吃", tone: "snack" },
      { primary: "刈包",     secondary: "小吃", tone: "snack" },
      { primary: "碗粿",     secondary: "小吃", tone: "snack" },
      { primary: "肉羹",     secondary: "小吃", tone: "snack" },
      { primary: "四神湯",    secondary: "小吃", tone: "snack" },
      { primary: "鹽水雞",    secondary: "小吃", tone: "snack" },
      { primary: "地瓜球",    secondary: "小吃", tone: "snack" },
      { primary: "蚵仔麵線",   secondary: "小吃", tone: "snack" },
      { primary: "水煎包",    secondary: "小吃", tone: "snack" },
      { primary: "筒仔米糕",   secondary: "小吃", tone: "snack" },
      { primary: "豬血糕",    secondary: "小吃", tone: "snack" },
      { primary: "甜不辣",    secondary: "小吃", tone: "snack" },
      { primary: "牛肉麵",    secondary: "麵食", tone: "noodle" },
      { primary: "麻醬麵",    secondary: "麵食", tone: "noodle" },
      { primary: "乾麵",     secondary: "麵食", tone: "noodle" },
      { primary: "意麵",     secondary: "麵食", tone: "noodle" },
      { primary: "炸醬麵",    secondary: "麵食", tone: "noodle" },
      { primary: "陽春麵",    secondary: "麵食", tone: "noodle" },
      { primary: "榨菜肉絲麵",  secondary: "麵食", tone: "noodle" },
      { primary: "酸辣麵",    secondary: "麵食", tone: "noodle" },
      { primary: "擔仔麵",    secondary: "麵食", tone: "noodle" },
      { primary: "鍋燒意麵",   secondary: "麵食", tone: "noodle" },
      { primary: "粄條",     secondary: "麵食", tone: "noodle" },
      { primary: "米粉湯",    secondary: "麵食", tone: "noodle" },
      { primary: "烏龍麵",    secondary: "麵食", tone: "noodle" },
      { primary: "刀削麵",    secondary: "麵食", tone: "noodle" },
      { primary: "大滷麵",    secondary: "麵食", tone: "noodle" },
      { primary: "羊肉麵",    secondary: "麵食", tone: "noodle" },
      { primary: "鴨肉麵",    secondary: "麵食", tone: "noodle" },
      { primary: "餛飩麵",    secondary: "麵食", tone: "noodle" },
      { primary: "什錦麵",    secondary: "麵食", tone: "noodle" },
      { primary: "麻辣麵",    secondary: "麵食", tone: "noodle" },
      { primary: "火雞肉飯",   secondary: "飯類", tone: "rice" },
      { primary: "排骨飯",    secondary: "飯類", tone: "rice" },
      { primary: "咖哩飯",    secondary: "飯類", tone: "rice" },
      { primary: "蛋炒飯",    secondary: "飯類", tone: "rice" },
      { primary: "燒肉丼",    secondary: "飯類", tone: "rice" },
      { primary: "爌肉飯",    secondary: "飯類", tone: "rice" },
      { primary: "雞腿便當",   secondary: "飯類", tone: "rice" },
      { primary: "鰻魚飯",    secondary: "飯類", tone: "rice" },
      { primary: "親子丼",    secondary: "飯類", tone: "rice" },
      { primary: "牛丼",     secondary: "飯類", tone: "rice" },
      { primary: "海南雞飯",   secondary: "飯類", tone: "rice" },
      { primary: "油飯",     secondary: "飯類", tone: "rice" },
      { primary: "廣東粥",    secondary: "飯類", tone: "rice" },
      { primary: "燴飯",     secondary: "飯類", tone: "rice" },
      { primary: "鐵板飯",    secondary: "飯類", tone: "rice" },
      { primary: "豬腳飯",    secondary: "飯類", tone: "rice" },
      { primary: "香腸飯",    secondary: "飯類", tone: "rice" },
      { primary: "蝦仁飯",    secondary: "飯類", tone: "rice" },
      { primary: "豬排飯",    secondary: "飯類", tone: "rice" },
      { primary: "三寶飯",    secondary: "飯類", tone: "rice" },
      { primary: "日式拉麵",   secondary: "異國", tone: "intl" },
      { primary: "壽司",     secondary: "異國", tone: "intl" },
      { primary: "韓式拌飯",   secondary: "異國", tone: "intl" },
      { primary: "打拋豬",    secondary: "異國", tone: "intl" },
      { primary: "義大利麵",   secondary: "異國", tone: "intl" },
      { primary: "披薩",     secondary: "異國", tone: "intl" },
      { primary: "漢堡",     secondary: "異國", tone: "intl" },
      { primary: "越南河粉",   secondary: "異國", tone: "intl" },
      { primary: "泰式綠咖哩",  secondary: "異國", tone: "intl" },
      { primary: "印度咖哩",   secondary: "異國", tone: "intl" },
      { primary: "墨西哥捲餅",  secondary: "異國", tone: "intl" },
      { primary: "日式咖哩",   secondary: "異國", tone: "intl" },
      { primary: "天婦羅",    secondary: "異國", tone: "intl" },
      { primary: "部隊鍋",    secondary: "異國", tone: "intl" },
      { primary: "韓式炸雞",   secondary: "異國", tone: "intl" },
      { primary: "燒肉",     secondary: "異國", tone: "intl" },
      { primary: "涮涮鍋",    secondary: "異國", tone: "intl" },
      { primary: "西班牙海鮮飯", secondary: "異國", tone: "intl" },
      { primary: "法式吐司",   secondary: "異國", tone: "intl" },
      { primary: "土耳其烤肉",  secondary: "異國", tone: "intl" },
      { primary: "沙威瑪",    secondary: "異國", tone: "intl" },
      { primary: "希臘沙拉",   secondary: "異國", tone: "intl" },
      { primary: "美式早午餐",  secondary: "異國", tone: "intl" },
      { primary: "生魚片丼",   secondary: "異國", tone: "intl" },
      { primary: "泡菜鍋",    secondary: "異國", tone: "intl" },
      { primary: "水餃",     secondary: "清爽", tone: "light" },
      { primary: "關東煮",    secondary: "清爽", tone: "light" },
      { primary: "生菜沙拉",   secondary: "清爽", tone: "light" },
      { primary: "涼麵",     secondary: "清爽", tone: "light" },
      { primary: "清粥小菜",   secondary: "清爽", tone: "light" },
      { primary: "蒸餃",     secondary: "清爽", tone: "light" },
      { primary: "鍋貼",     secondary: "清爽", tone: "light" },
      { primary: "燙青菜",    secondary: "清爽", tone: "light" },
      { primary: "味噌定食",   secondary: "清爽", tone: "light" },
      { primary: "豆腐煲",    secondary: "清爽", tone: "light" },
      { primary: "蔬食自助餐",  secondary: "清爽", tone: "light" },
      { primary: "素食便當",   secondary: "清爽", tone: "light" },
      { primary: "鮮蔬湯麵",   secondary: "清爽", tone: "light" },
      { primary: "雞肉沙拉",   secondary: "清爽", tone: "light" },
      { primary: "蛤蜊湯麵",   secondary: "清爽", tone: "light" }
    ]
  },
  {
    id: "cuisine", icon: "🌍", label: "吃哪一國料理", size: "md",
    hint: "想換換口味？點一下球",
    initial: { primary: "哪一國？", secondary: "點一下球" },
    noRepeat: true,
    items: [
      { primary: "台灣",   secondary: "亞洲", tone: "asia" },
      { primary: "日本",   secondary: "亞洲", tone: "asia" },
      { primary: "韓國",   secondary: "亞洲", tone: "asia" },
      { primary: "中國",   secondary: "亞洲", tone: "asia" },
      { primary: "泰國",   secondary: "亞洲", tone: "asia" },
      { primary: "越南",   secondary: "亞洲", tone: "asia" },
      { primary: "印度",   secondary: "亞洲", tone: "asia" },
      { primary: "印尼",   secondary: "亞洲", tone: "asia" },
      { primary: "馬來西亞", secondary: "亞洲", tone: "asia" },
      { primary: "新加坡",  secondary: "亞洲", tone: "asia" },
      { primary: "菲律賓",  secondary: "亞洲", tone: "asia" },
      { primary: "緬甸",   secondary: "亞洲", tone: "asia" },
      { primary: "柬埔寨",  secondary: "亞洲", tone: "asia" },
      { primary: "尼泊爾",  secondary: "亞洲", tone: "asia" },
      { primary: "斯里蘭卡", secondary: "亞洲", tone: "asia" },
      { primary: "蒙古",   secondary: "亞洲", tone: "asia" },
      { primary: "寮國",   secondary: "亞洲", tone: "asia" },
      { primary: "香港",   secondary: "亞洲", tone: "asia" },
      { primary: "義大利",  secondary: "歐洲", tone: "europe" },
      { primary: "法國",   secondary: "歐洲", tone: "europe" },
      { primary: "西班牙",  secondary: "歐洲", tone: "europe" },
      { primary: "德國",   secondary: "歐洲", tone: "europe" },
      { primary: "英國",   secondary: "歐洲", tone: "europe" },
      { primary: "希臘",   secondary: "歐洲", tone: "europe" },
      { primary: "葡萄牙",  secondary: "歐洲", tone: "europe" },
      { primary: "荷蘭",   secondary: "歐洲", tone: "europe" },
      { primary: "比利時",  secondary: "歐洲", tone: "europe" },
      { primary: "瑞士",   secondary: "歐洲", tone: "europe" },
      { primary: "奧地利",  secondary: "歐洲", tone: "europe" },
      { primary: "瑞典",   secondary: "歐洲", tone: "europe" },
      { primary: "丹麥",   secondary: "歐洲", tone: "europe" },
      { primary: "波蘭",   secondary: "歐洲", tone: "europe" },
      { primary: "匈牙利",  secondary: "歐洲", tone: "europe" },
      { primary: "俄羅斯",  secondary: "歐洲", tone: "europe" },
      { primary: "美國",   secondary: "美洲", tone: "america" },
      { primary: "墨西哥",  secondary: "美洲", tone: "america" },
      { primary: "巴西",   secondary: "美洲", tone: "america" },
      { primary: "秘魯",   secondary: "美洲", tone: "america" },
      { primary: "阿根廷",  secondary: "美洲", tone: "america" },
      { primary: "古巴",   secondary: "美洲", tone: "america" },
      { primary: "牙買加",  secondary: "美洲", tone: "america" },
      { primary: "加拿大",  secondary: "美洲", tone: "america" },
      { primary: "智利",   secondary: "美洲", tone: "america" },
      { primary: "哥倫比亞", secondary: "美洲", tone: "america" },
      { primary: "摩洛哥",  secondary: "非洲", tone: "africa" },
      { primary: "埃及",   secondary: "非洲", tone: "africa" },
      { primary: "衣索比亞", secondary: "非洲", tone: "africa" },
      { primary: "土耳其",  secondary: "中東", tone: "mideast" },
      { primary: "黎巴嫩",  secondary: "中東", tone: "mideast" },
      { primary: "以色列",  secondary: "中東", tone: "mideast" }
    ]
  },
  {
    id: "drink", icon: "🧋", label: "喝什麼飲料", size: "md",
    hint: "口渴了？點一下球",
    initial: { primary: "喝什麼？", secondary: "點一下球" },
    noRepeat: true,
    items: [
      { primary: "珍珠奶茶",   secondary: "茶飲", tone: "tea" },
      { primary: "四季春",    secondary: "茶飲", tone: "tea" },
      { primary: "檸檬紅茶",   secondary: "茶飲", tone: "tea" },
      { primary: "多多綠",    secondary: "茶飲", tone: "tea" },
      { primary: "冬瓜檸檬",   secondary: "茶飲", tone: "tea" },
      { primary: "烏龍拿鐵",   secondary: "茶飲", tone: "tea" },
      { primary: "紅茶拿鐵",   secondary: "茶飲", tone: "tea" },
      { primary: "無糖青茶",   secondary: "茶飲", tone: "tea" },
      { primary: "阿薩姆奶茶",  secondary: "茶飲", tone: "tea" },
      { primary: "鮮奶茶",    secondary: "茶飲", tone: "tea" },
      { primary: "蜂蜜綠茶",   secondary: "茶飲", tone: "tea" },
      { primary: "百香雙響炮",  secondary: "茶飲", tone: "tea" },
      { primary: "梅子綠茶",   secondary: "茶飲", tone: "tea" },
      { primary: "桂花烏龍",   secondary: "茶飲", tone: "tea" },
      { primary: "茉莉綠茶",   secondary: "茶飲", tone: "tea" },
      { primary: "抹茶拿鐵",   secondary: "茶飲", tone: "tea" },
      { primary: "黑糖珍珠鮮奶", secondary: "茶飲", tone: "tea" },
      { primary: "芋頭鮮奶",   secondary: "茶飲", tone: "tea" },
      { primary: "蕎麥茶",    secondary: "茶飲", tone: "tea" },
      { primary: "麥茶",     secondary: "茶飲", tone: "tea" },
      { primary: "決明子茶",   secondary: "茶飲", tone: "tea" },
      { primary: "洛神花茶",   secondary: "茶飲", tone: "tea" },
      { primary: "玫瑰花茶",   secondary: "茶飲", tone: "tea" },
      { primary: "菊花茶",    secondary: "茶飲", tone: "tea" },
      { primary: "普洱茶",    secondary: "茶飲", tone: "tea" },
      { primary: "東方美人茶",  secondary: "茶飲", tone: "tea" },
      { primary: "鐵觀音",    secondary: "茶飲", tone: "tea" },
      { primary: "高山烏龍",   secondary: "茶飲", tone: "tea" },
      { primary: "荔枝紅茶",   secondary: "茶飲", tone: "tea" },
      { primary: "葡萄柚綠茶",  secondary: "茶飲", tone: "tea" },
      { primary: "美式咖啡",   secondary: "咖啡", tone: "coffee" },
      { primary: "拿鐵",     secondary: "咖啡", tone: "coffee" },
      { primary: "卡布奇諾",   secondary: "咖啡", tone: "coffee" },
      { primary: "摩卡",     secondary: "咖啡", tone: "coffee" },
      { primary: "濃縮咖啡",   secondary: "咖啡", tone: "coffee" },
      { primary: "焦糖瑪奇朵",  secondary: "咖啡", tone: "coffee" },
      { primary: "冰滴咖啡",   secondary: "咖啡", tone: "coffee" },
      { primary: "手沖單品",   secondary: "咖啡", tone: "coffee" },
      { primary: "維也納咖啡",  secondary: "咖啡", tone: "coffee" },
      { primary: "康寶藍",    secondary: "咖啡", tone: "coffee" },
      { primary: "澳白",     secondary: "咖啡", tone: "coffee" },
      { primary: "燕麥奶拿鐵",  secondary: "咖啡", tone: "coffee" },
      { primary: "豆漿拿鐵",   secondary: "咖啡", tone: "coffee" },
      { primary: "咖啡歐蕾",   secondary: "咖啡", tone: "coffee" },
      { primary: "黑咖啡",    secondary: "咖啡", tone: "coffee" },
      { primary: "冰美式",    secondary: "咖啡", tone: "coffee" },
      { primary: "冰拿鐵",    secondary: "咖啡", tone: "coffee" },
      { primary: "榛果拿鐵",   secondary: "咖啡", tone: "coffee" },
      { primary: "香草拿鐵",   secondary: "咖啡", tone: "coffee" },
      { primary: "越南咖啡",   secondary: "咖啡", tone: "coffee" },
      { primary: "氣泡水",    secondary: "無糖", tone: "fizz" },
      { primary: "檸檬水",    secondary: "無糖", tone: "fizz" },
      { primary: "無糖綠茶",   secondary: "無糖", tone: "fizz" },
      { primary: "運動飲料",   secondary: "無糖", tone: "fizz" },
      { primary: "蘇打水",    secondary: "無糖", tone: "fizz" },
      { primary: "檸檬氣泡水",  secondary: "無糖", tone: "fizz" },
      { primary: "葡萄柚氣泡水", secondary: "無糖", tone: "fizz" },
      { primary: "白開水",    secondary: "無糖", tone: "fizz" },
      { primary: "礦泉水",    secondary: "無糖", tone: "fizz" },
      { primary: "椰子水",    secondary: "無糖", tone: "fizz" },
      { primary: "大麥茶",    secondary: "無糖", tone: "fizz" },
      { primary: "玉米鬚茶",   secondary: "無糖", tone: "fizz" },
      { primary: "黑豆水",    secondary: "無糖", tone: "fizz" },
      { primary: "檸檬蜂蜜水",  secondary: "無糖", tone: "fizz" },
      { primary: "薄荷水",    secondary: "無糖", tone: "fizz" },
      { primary: "蘋果醋飲",   secondary: "無糖", tone: "fizz" },
      { primary: "康普茶",    secondary: "無糖", tone: "fizz" },
      { primary: "電解質水",   secondary: "無糖", tone: "fizz" },
      { primary: "無糖紅茶",   secondary: "無糖", tone: "fizz" },
      { primary: "仙草茶",    secondary: "無糖", tone: "fizz" },
      { primary: "豆漿",     secondary: "其他", tone: "sweet" },
      { primary: "鮮果汁",    secondary: "其他", tone: "sweet" },
      { primary: "熱可可",    secondary: "其他", tone: "sweet" },
      { primary: "優酪乳",    secondary: "其他", tone: "sweet" },
      { primary: "柳橙汁",    secondary: "其他", tone: "sweet" },
      { primary: "蘋果汁",    secondary: "其他", tone: "sweet" },
      { primary: "葡萄汁",    secondary: "其他", tone: "sweet" },
      { primary: "芒果汁",    secondary: "其他", tone: "sweet" },
      { primary: "西瓜汁",    secondary: "其他", tone: "sweet" },
      { primary: "木瓜牛奶",   secondary: "其他", tone: "sweet" },
      { primary: "香蕉牛奶",   secondary: "其他", tone: "sweet" },
      { primary: "酪梨牛奶",   secondary: "其他", tone: "sweet" },
      { primary: "甘蔗汁",    secondary: "其他", tone: "sweet" },
      { primary: "蘆薈汁",    secondary: "其他", tone: "sweet" },
      { primary: "蔓越莓汁",   secondary: "其他", tone: "sweet" },
      { primary: "番茄汁",    secondary: "其他", tone: "sweet" },
      { primary: "綜合果汁",   secondary: "其他", tone: "sweet" },
      { primary: "鳳梨汁",    secondary: "其他", tone: "sweet" },
      { primary: "檸檬愛玉",   secondary: "其他", tone: "sweet" },
      { primary: "仙草蜜",    secondary: "其他", tone: "sweet" },
      { primary: "燒仙草",    secondary: "其他", tone: "sweet" },
      { primary: "杏仁茶",    secondary: "其他", tone: "sweet" },
      { primary: "米漿",     secondary: "其他", tone: "sweet" },
      { primary: "薏仁漿",    secondary: "其他", tone: "sweet" },
      { primary: "養樂多",    secondary: "其他", tone: "sweet" },
      { primary: "鮮奶",     secondary: "其他", tone: "sweet" },
      { primary: "巧克力牛奶",  secondary: "其他", tone: "sweet" },
      { primary: "草莓牛奶",   secondary: "其他", tone: "sweet" },
      { primary: "冬瓜茶",    secondary: "其他", tone: "sweet" },
      { primary: "青草茶",    secondary: "其他", tone: "sweet" }
    ]
  },
  {
    id: "midnight", icon: "🌙", label: "吃什麼宵夜", size: "md",
    hint: "半夜餓了？點一下球",
    initial: { primary: "吃什麼？", secondary: "點一下球" },
    noRepeat: true,
    items: [
      { primary: "鹹酥雞",    secondary: "鹹食", tone: "snack" },
      { primary: "滷味",     secondary: "鹹食", tone: "snack" },
      { primary: "烤香腸",    secondary: "鹹食", tone: "snack" },
      { primary: "蔥抓餅",    secondary: "鹹食", tone: "snack" },
      { primary: "雞排",     secondary: "鹹食", tone: "snack" },
      { primary: "熱狗",     secondary: "鹹食", tone: "snack" },
      { primary: "甜不辣",    secondary: "鹹食", tone: "snack" },
      { primary: "鹽酥菇",    secondary: "鹹食", tone: "snack" },
      { primary: "炸物拼盤",   secondary: "鹹食", tone: "snack" },
      { primary: "鹽水雞",    secondary: "鹹食", tone: "snack" },
      { primary: "烤玉米",    secondary: "鹹食", tone: "snack" },
      { primary: "烤肉串",    secondary: "鹹食", tone: "snack" },
      { primary: "章魚燒",    secondary: "鹹食", tone: "snack" },
      { primary: "大阪燒",    secondary: "鹹食", tone: "snack" },
      { primary: "蔥油餅",    secondary: "鹹食", tone: "snack" },
      { primary: "蘿蔔糕",    secondary: "鹹食", tone: "snack" },
      { primary: "蛋餅",     secondary: "鹹食", tone: "snack" },
      { primary: "起司球",    secondary: "鹹食", tone: "snack" },
      { primary: "薯條",     secondary: "鹹食", tone: "snack" },
      { primary: "洋蔥圈",    secondary: "鹹食", tone: "snack" },
      { primary: "雞塊",     secondary: "鹹食", tone: "snack" },
      { primary: "花枝丸",    secondary: "鹹食", tone: "snack" },
      { primary: "米血",     secondary: "鹹食", tone: "snack" },
      { primary: "豆干",     secondary: "鹹食", tone: "snack" },
      { primary: "燒餅",     secondary: "鹹食", tone: "snack" },
      { primary: "泡麵",     secondary: "麵食", tone: "noodle" },
      { primary: "陽春麵",    secondary: "麵食", tone: "noodle" },
      { primary: "米粉湯",    secondary: "麵食", tone: "noodle" },
      { primary: "餛飩湯",    secondary: "麵食", tone: "noodle" },
      { primary: "麻油麵線",   secondary: "麵食", tone: "noodle" },
      { primary: "大腸麵線",   secondary: "麵食", tone: "noodle" },
      { primary: "牛肉湯麵",   secondary: "麵食", tone: "noodle" },
      { primary: "榨菜肉絲麵",  secondary: "麵食", tone: "noodle" },
      { primary: "沙茶麵",    secondary: "麵食", tone: "noodle" },
      { primary: "麻辣鴨血麵",  secondary: "麵食", tone: "noodle" },
      { primary: "乾拌麵",    secondary: "麵食", tone: "noodle" },
      { primary: "韓式泡麵",   secondary: "麵食", tone: "noodle" },
      { primary: "烏龍湯麵",   secondary: "麵食", tone: "noodle" },
      { primary: "意麵湯",    secondary: "麵食", tone: "noodle" },
      { primary: "冬粉湯",    secondary: "麵食", tone: "noodle" },
      { primary: "米苔目",    secondary: "麵食", tone: "noodle" },
      { primary: "肉燥麵",    secondary: "麵食", tone: "noodle" },
      { primary: "酸辣湯麵",   secondary: "麵食", tone: "noodle" },
      { primary: "蚵仔麵線",   secondary: "麵食", tone: "noodle" },
      { primary: "排骨酥麵",   secondary: "麵食", tone: "noodle" },
      { primary: "炸雞",     secondary: "異國", tone: "intl" },
      { primary: "披薩",     secondary: "異國", tone: "intl" },
      { primary: "日式串燒",   secondary: "異國", tone: "intl" },
      { primary: "韓式炸雞",   secondary: "異國", tone: "intl" },
      { primary: "漢堡",     secondary: "異國", tone: "intl" },
      { primary: "燒烤",     secondary: "異國", tone: "intl" },
      { primary: "拉麵",     secondary: "異國", tone: "intl" },
      { primary: "壽司捲",    secondary: "異國", tone: "intl" },
      { primary: "泰式炒河粉",  secondary: "異國", tone: "intl" },
      { primary: "越式法國麵包", secondary: "異國", tone: "intl" },
      { primary: "墨西哥玉米片", secondary: "異國", tone: "intl" },
      { primary: "起司薯條",   secondary: "異國", tone: "intl" },
      { primary: "美式熱狗堡",  secondary: "異國", tone: "intl" },
      { primary: "韓式辣炒年糕", secondary: "異國", tone: "intl" },
      { primary: "日式煎餃",   secondary: "異國", tone: "intl" },
      { primary: "天婦羅",    secondary: "異國", tone: "intl" },
      { primary: "韓式部隊鍋",  secondary: "異國", tone: "intl" },
      { primary: "印度烤餅",   secondary: "異國", tone: "intl" },
      { primary: "沙嗲串",    secondary: "異國", tone: "intl" },
      { primary: "咖哩魚蛋",   secondary: "異國", tone: "intl" },
      { primary: "關東煮",    secondary: "清爽", tone: "light" },
      { primary: "瘦肉粥",    secondary: "清爽", tone: "light" },
      { primary: "茶葉蛋",    secondary: "清爽", tone: "light" },
      { primary: "水果",     secondary: "清爽", tone: "light" },
      { primary: "味噌湯",    secondary: "清爽", tone: "light" },
      { primary: "湯餃",     secondary: "清爽", tone: "light" },
      { primary: "蔬菜湯",    secondary: "清爽", tone: "light" },
      { primary: "清粥",     secondary: "清爽", tone: "light" },
      { primary: "涼拌小黃瓜",  secondary: "清爽", tone: "light" },
      { primary: "毛豆",     secondary: "清爽", tone: "light" },
      { primary: "沙拉",     secondary: "清爽", tone: "light" },
      { primary: "優格",     secondary: "清爽", tone: "light" },
      { primary: "玉米濃湯",   secondary: "清爽", tone: "light" },
      { primary: "豆漿",     secondary: "清爽", tone: "light" },
      { primary: "蒸蛋",     secondary: "清爽", tone: "light" },
      { primary: "燙青菜",    secondary: "清爽", tone: "light" },
      { primary: "冬瓜湯",    secondary: "清爽", tone: "light" },
      { primary: "蛤蜊湯",    secondary: "清爽", tone: "light" },
      { primary: "雞湯",     secondary: "清爽", tone: "light" },
      { primary: "海帶芽湯",   secondary: "清爽", tone: "light" },
      { primary: "豆花",     secondary: "甜食", tone: "sweet" },
      { primary: "雞蛋糕",    secondary: "甜食", tone: "sweet" },
      { primary: "紅豆湯",    secondary: "甜食", tone: "sweet" },
      { primary: "綿綿冰",    secondary: "甜食", tone: "sweet" },
      { primary: "芋圓",     secondary: "甜食", tone: "sweet" },
      { primary: "燒仙草",    secondary: "甜食", tone: "sweet" },
      { primary: "布丁",     secondary: "甜食", tone: "sweet" },
      { primary: "銅鑼燒",    secondary: "甜食", tone: "sweet" },
      { primary: "鯛魚燒",    secondary: "甜食", tone: "sweet" },
      { primary: "泡芙",     secondary: "甜食", tone: "sweet" },
      { primary: "蛋塔",     secondary: "甜食", tone: "sweet" },
      { primary: "麻糬",     secondary: "甜食", tone: "sweet" },
      { primary: "甜甜圈",    secondary: "甜食", tone: "sweet" },
      { primary: "巧克力",    secondary: "甜食", tone: "sweet" },
      { primary: "冰淇淋",    secondary: "甜食", tone: "sweet" }
    ]
  },
  {
    id: "punish", icon: "🎭", label: "抽個懲罰", size: "md",
    hint: "願賭服輸，點一下球",
    initial: { primary: "抽什麼？", secondary: "點一下球" },
    noRepeat: true,
    items: [
      { primary: "做鬼臉10秒", secondary: "表演", tone: "perform" },
      { primary: "學一種動物叫", secondary: "表演", tone: "perform" },
      { primary: "唱一段歌",   secondary: "表演", tone: "perform" },
      { primary: "跳一段舞",   secondary: "表演", tone: "perform" },
      { primary: "模仿一位名人", secondary: "表演", tone: "perform" },
      { primary: "表演一個魔術", secondary: "表演", tone: "perform" },
      { primary: "用假音講話",  secondary: "表演", tone: "perform" },
      { primary: "演一段台詞",  secondary: "表演", tone: "perform" },
      { primary: "深蹲10下",  secondary: "動作", tone: "action" },
      { primary: "單腳站30秒", secondary: "動作", tone: "action" },
      { primary: "原地跳20下", secondary: "動作", tone: "action" },
      { primary: "伏地挺身5下", secondary: "動作", tone: "action" },
      { primary: "學螃蟹走路",  secondary: "動作", tone: "action" },
      { primary: "定格10秒",  secondary: "動作", tone: "action" },
      { primary: "原地轉5圈",  secondary: "動作", tone: "action" },
      { primary: "稱讚每個人",  secondary: "說話", tone: "talk" },
      { primary: "講一個冷笑話", secondary: "說話", tone: "talk" },
      { primary: "說出三個優點", secondary: "說話", tone: "talk" },
      { primary: "用台語說一句", secondary: "說話", tone: "talk" },
      { primary: "講一件糗事",  secondary: "說話", tone: "talk" },
      { primary: "背一首唐詩",  secondary: "說話", tone: "talk" },
      { primary: "英文自我介紹", secondary: "說話", tone: "talk" },
      { primary: "大聲說我最棒", secondary: "說話", tone: "talk" },
      { primary: "請大家喝飲料", secondary: "任務", tone: "task" },
      { primary: "負責收桌子",  secondary: "任務", tone: "task" },
      { primary: "幫大家拍合照", secondary: "任務", tone: "task" },
      { primary: "下輪幫忙點餐", secondary: "任務", tone: "task" },
      { primary: "用怪腔調說話", secondary: "搞怪", tone: "silly" },
      { primary: "頂東西走一圈", secondary: "搞怪", tone: "silly" },
      { primary: "帽子反戴到底", secondary: "搞怪", tone: "silly" }
    ]
  },
  {
    id: "dice", icon: "🎲", label: "擲骰子", size: "xl",
    hint: "點一下球，擲出點數",
    initial: { primary: "?", secondary: "點一下球" },
    items: [
      { primary: "⚀", secondary: "1 點", tone: "" },
      { primary: "⚁", secondary: "2 點", tone: "" },
      { primary: "⚂", secondary: "3 點", tone: "" },
      { primary: "⚃", secondary: "4 點", tone: "" },
      { primary: "⚄", secondary: "5 點", tone: "" },
      { primary: "⚅", secondary: "6 點", tone: "" }
    ]
  },
  {
    id: "number", icon: "🔢", label: "0～100 猜數字", size: "xl",
    hint: "點一下球，抽一個數字",
    initial: { primary: "?", secondary: "0 – 100" },
    // 101 個值列成清單太蠢，直接算
    roll: () => ({ primary: String(Math.floor(Math.random() * 101)), secondary: "0 – 100" })
  },
  {
    id: "yesno", icon: "⚖️", label: "Yes or No", size: "lg",
    hint: "問一個是非題，點一下球",
    initial: { primary: "?", secondary: "點一下球" },
    items: [
      { primary: "YES", secondary: "是", tone: "yes" },
      { primary: "NO",  secondary: "否", tone: "no" }
    ]
  },
  {
    id: "compass", icon: "🧭", label: "往哪走", size: "xl",
    hint: "不知道往哪走？點一下球",
    initial: { primary: "?", secondary: "點一下球" },
    items: [
      { primary: "⬆️", secondary: "前", tone: "" },
      { primary: "↗️", secondary: "右前", tone: "" },
      { primary: "➡️", secondary: "右", tone: "" },
      { primary: "↘️", secondary: "右後", tone: "" },
      { primary: "⬇️", secondary: "後", tone: "" },
      { primary: "↙️", secondary: "左後", tone: "" },
      { primary: "⬅️", secondary: "左", tone: "" },
      { primary: "↖️", secondary: "左前", tone: "" }
    ]
  }
];
